### ISSUE TITLE
User "system:serviceaccount:tqvarnst:pipeline" cannot get resource "virtualmachineinstances" in API group "kubevirt.io

### ISSUE THREAD

**Issue by cmoulliard** [q-shift/qshift-templates#15]
## TODO

Update the ClusterRoleBinding of the `sa:pipeline` to give it access to kubevirt.io API within the namespace of the application AND NOT as this is the case under `qshift-test` namespace.

Example
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt.io:view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevirt.io:view
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: qshift-test
```
