### ISSUE TITLE
Set a default value for the backstage owner

### ISSUE THREAD

**Issue by cmoulliard** [q-shift/qshift-templates#39]
## TODO

Set a default value for the backstage owner
```
        owner:
          title: Owner
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
          default: user:guest
```
