### ISSUE TITLE
argocd action Error: Duplicate project detected. Cannot overwrite existing

### ISSUE THREAD

**Issue by cmoulliard** [q-shift/qshift-templates#7]
## Issue

When wereplay the templaet using PR #5 then process fails
```
882024-02-09T11:29:00.000Z Error: Duplicate project detected. Cannot overwrite existing.89    at 
ArgoService.createArgoProject (/Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/src/service/argocd.service.ts:264:13)90    at 
process.processTicksAndRejections (node:internal/process/task_queues:95:5)91    at 
ArgoService.createArgoResources (/Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/src/service/argocd.service.ts:686:5)92    at 
Object.handler (/Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/scaffolder-backend-argocd/src/actions/run/argocd.ts:59:7)93    at 
NunjucksWorkflowRunner.executeStep (/Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:343:9)94    at 
NunjucksWorkflowRunner.execute (/Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:431:9)95    at 
TaskWorker.runOneTask (/Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:145:26)96    at 
async run (/Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/p-queue/dist/index.js:163:29)
```
![Screenshot 2024-02-09 at 12 33 08](https://github.com/q-shift/qshift-templates/assets/463790/2de20aa7-f336-4a6d-bc87-d3133ac08c2a)

**Comment by cmoulliard** [comment]
As this Argocd project `my-quarkus-app-bootstrap` already exists, then that fails. If we delete it, then the problem is gone.

I'm wondering how such argocd projects have been created as our templates use the default
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.component_id }}-test
  namespace: ${{ values.gitopsNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
```
