### ISSUE TITLE
Suggestion: Add the link of the Openshift route exposing the quarkus application

### ISSUE THREAD

**Issue by cmoulliard** [q-shift/qshift-templates#9]
## Suggestion

Add the link/url of the OpenShift Route exposing the quarkus application within the Component 

See doc: https://backstage.io/docs/features/software-catalog/descriptor-format/#links-optional

Example of links:

```yaml
kind: Component
metadata:
  name: "my-quarkus-app"
  description: "A cool quarkus app"
  annotations:
    argocd/app-name: my-quarkus-app-dev
    backstage.io/kubernetes-id: my-quarkus-app
    backstage.io/kubernetes-namespace: my-quarkus-app-dev
    janus-idp.io/tekton: my-quarkus-app
    backstage.io/source-location: url:https://gitlab-gitlab.apps.cluster-8z65j.sandbox1430.opentlc.com/development/my-quarkus-app
    backstage.io/techdocs-ref: url:https://gitlab-gitlab.apps.cluster-8z65j.sandbox1430.opentlc.com/development/my-quarkus-app
    gitlab.com/project-slug: development/my-quarkus-app
    quay.io/repository-slug: "quayadmin/my-quarkus-app"
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-8z65j.sandbox1430.opentlc.com/#https://gitlab-gitlab.apps.cluster-8z65j.sandbox1430.opentlc.com/development/my-quarkus-app
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-8z65j.sandbox1430.opentlc.com/#https://gitlab-gitlab.apps.cluster-8z65j.sandbox1430.opentlc.com/development/my-quarkus-app?che-editor=che-incubator/che-idea/latest
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
```
WDYT ? @iocanel @aureamunoz

**Comment by cmoulliard** [comment]
An alternative is also to use the text tag which displasy if we click on the link additional information
```
  output:
    links:
      - title: Open the Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open the Catalog Info Component
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
    text:
      - title: More information
        content: |
          **Entity URL:** `${{ steps['publish'].output.remoteUrl }}`
```
![Screenshot 2024-02-12 at 19 15 15](https://github.com/q-shift/qshift-templates/assets/463790/79d0cdac-d3e2-4611-8f38-84c0cef0dce7)

**Comment by aureamunoz** [comment]
Ah, I think it's useful to add the link, yes. I vote for it

**Comment by iocanel** [comment]
Why did the `quarkus-wizzard` crept back in? We had it removed a couple of weeks ago.

**Comment by cmoulliard** [comment]
> Why did the `quarkus-wizzard` crept back in? We had it removed a couple of weeks ago.

This is a screenshot that I took from dummy template that I tested locally to show how this code
```
text:
      - title: More information
        content: |
          **Entity URL:** `${{ steps['publish'].output.remoteUrl }}`
```
is rendered
